---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: 'ensap'
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Generate DEB and RPM using NFPM
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage: https://github.com/riton/ensap-cli
    description: Ensap (https://ensap.gouv.fr) CLI - L'espace numérique sécurisé de l'agent public
    maintainer: Remi Ferrand <riton.github_at_gmail.com>
    license: CeCILL-B
    vendor: Remi Ferrand <riton.github_at_gmail.com>
    formats:
      - apk
      - deb
      - rpm
    bindir: '/usr/bin'
    contents:
      - src: ./_examples/ensap.yaml
        dst: /usr/share/{{ .ProjectName }}/ensap.sample.yaml
